### ISSUE TITLE
inplace-abn

### ISSUE THREAD

**Issue by QinghuanWei** [markusschoen/MGNet#1]
i get the error when i do
python3 -m pip install -r requirements.txt

'''
Building wheel for inplace-abn (setup.py) ... error
  error: subprocess-exited-with-error
'''

**Comment by markusschoen** [comment]
Which OS and CUDA version are you using?
Please run `python3 -m pip install inplace-abn` and post the full output.

**Comment by QinghuanWei** [comment]
My system is Ubuntu 18.04 and the cuda version is 11.0. I tried this and it didn't work, I managed to install it by downloading the source code and compiling it. Now I have a new problem, when I run
`python tools/demo.py --config-file configs/MGNet-KITTI-Eigen-Zhou.yaml --input test_image/test1.jpg --calibration-file calibration --output result --opts MODEL.WEIGHTS checkpoint/model_kitti_zhou.pth`
i get the error
` ` `
Traceback (most recent call last):
  File "tools/demo.py", line 240, in <module>
    demo = VisualizationDemo(cfg, args.calibration_file, args.show_pcl)
  File "tools/demo.py", line 37, in __init__
    self.predictor = MGNetPredictor(cfg, calibration_file)
  File "/root/data/lixiyuan/MGNet/MGNet-main/mgnet/inference/predictor.py", line 41, in __init__
    self.calibration_info = json.load(f)
  File "/root/anaconda3/envs/lixiyuan/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/root/anaconda3/envs/lixiyuan/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/lixiyuan/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/lixiyuan/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
` ` `

**Comment by markusschoen** [comment]
Great, that you managed to install inplace-abn.
Regarding the new problem: The calibration file needs to be a json file in Cityscapes-Camera-Format and should contain at least the intrinsic parameters and the extrinsic z component.
